on:
  push:
    branches:
    - main

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Plain Export Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: './tbta_export_to_word.py'
          requirements: './requirements.txt'
          upload_exe_with_name: 'tbta_export_to_word'
          options: --onefile, --noconsole
      - name: Create Table Export Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: './tbta_export_to_table.py'
          requirements: './requirements.txt'
          upload_exe_with_name: 'tbta_export_to_table'
          options: --onefile, --noconsole